// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cardio_and_sets.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createCardioAndSets = `-- name: CreateCardioAndSets :one
INSERT INTO cardio_and_sets(id, workout_exercises_id, set_number, distance, is_kilometers, duration_seconds, created_at, updated_at)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, workout_exercises_id, set_number, distance, is_kilometers, duration_seconds, created_at, updated_at
`

type CreateCardioAndSetsParams struct {
	ID                 uuid.UUID
	WorkoutExercisesID uuid.UUID
	SetNumber          int32
	Distance           sql.NullFloat64
	IsKilometers       bool
	DurationSeconds    sql.NullInt32
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) CreateCardioAndSets(ctx context.Context, arg CreateCardioAndSetsParams) (CardioAndSet, error) {
	row := q.db.QueryRowContext(ctx, createCardioAndSets,
		arg.ID,
		arg.WorkoutExercisesID,
		arg.SetNumber,
		arg.Distance,
		arg.IsKilometers,
		arg.DurationSeconds,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CardioAndSet
	err := row.Scan(
		&i.ID,
		&i.WorkoutExercisesID,
		&i.SetNumber,
		&i.Distance,
		&i.IsKilometers,
		&i.DurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCardioAndSets = `-- name: DeleteCardioAndSets :exec
DELETE FROM cardio_and_sets
WHERE id = $1 AND workout_exercises_id = $2
`

type DeleteCardioAndSetsParams struct {
	ID                 uuid.UUID
	WorkoutExercisesID uuid.UUID
}

func (q *Queries) DeleteCardioAndSets(ctx context.Context, arg DeleteCardioAndSetsParams) error {
	_, err := q.db.ExecContext(ctx, deleteCardioAndSets, arg.ID, arg.WorkoutExercisesID)
	return err
}

const getAllCardioFromSession = `-- name: GetAllCardioFromSession :many
SELECT id, workout_exercises_id, set_number, distance, is_kilometers, duration_seconds, created_at, updated_at FROM cardio_and_sets
WHERE workout_exercises_id = $1
`

func (q *Queries) GetAllCardioFromSession(ctx context.Context, workoutExercisesID uuid.UUID) ([]CardioAndSet, error) {
	rows, err := q.db.QueryContext(ctx, getAllCardioFromSession, workoutExercisesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardioAndSet
	for rows.Next() {
		var i CardioAndSet
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutExercisesID,
			&i.SetNumber,
			&i.Distance,
			&i.IsKilometers,
			&i.DurationSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSetsDistance = `-- name: GetAllSetsDistance :one
SELECT SUM(distance) FROM cardio_and_sets
WHERE workout_exercises_id = $1
`

func (q *Queries) GetAllSetsDistance(ctx context.Context, workoutExercisesID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAllSetsDistance, workoutExercisesID)
	var sum int64
	err := row.Scan(&sum)
	return sum, err
}

const getAllSetsDuration = `-- name: GetAllSetsDuration :one
SELECT SUM(duration_seconds) FROM cardio_and_sets
WHERE workout_exercises_id = $1
`

func (q *Queries) GetAllSetsDuration(ctx context.Context, workoutExercisesID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAllSetsDuration, workoutExercisesID)
	var sum int64
	err := row.Scan(&sum)
	return sum, err
}

const getCardioAndSetFromID = `-- name: GetCardioAndSetFromID :one
SELECT id, workout_exercises_id, set_number, distance, is_kilometers, duration_seconds, created_at, updated_at FROM cardio_and_sets
WHERE id = $1
`

func (q *Queries) GetCardioAndSetFromID(ctx context.Context, id uuid.UUID) (CardioAndSet, error) {
	row := q.db.QueryRowContext(ctx, getCardioAndSetFromID, id)
	var i CardioAndSet
	err := row.Scan(
		&i.ID,
		&i.WorkoutExercisesID,
		&i.SetNumber,
		&i.Distance,
		&i.IsKilometers,
		&i.DurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSetDistance = `-- name: GetSetDistance :one
SELECT distance FROM cardio_and_sets
WHERE id = $1 AND workout_exercises_id = $2
`

type GetSetDistanceParams struct {
	ID                 uuid.UUID
	WorkoutExercisesID uuid.UUID
}

func (q *Queries) GetSetDistance(ctx context.Context, arg GetSetDistanceParams) (sql.NullFloat64, error) {
	row := q.db.QueryRowContext(ctx, getSetDistance, arg.ID, arg.WorkoutExercisesID)
	var distance sql.NullFloat64
	err := row.Scan(&distance)
	return distance, err
}

const getSetDuration = `-- name: GetSetDuration :one
SELECT duration_seconds FROM cardio_and_sets
WHERE id = $1 AND workout_exercises_id = $2
`

type GetSetDurationParams struct {
	ID                 uuid.UUID
	WorkoutExercisesID uuid.UUID
}

func (q *Queries) GetSetDuration(ctx context.Context, arg GetSetDurationParams) (sql.NullInt32, error) {
	row := q.db.QueryRowContext(ctx, getSetDuration, arg.ID, arg.WorkoutExercisesID)
	var duration_seconds sql.NullInt32
	err := row.Scan(&duration_seconds)
	return duration_seconds, err
}

const updateCardioAndSets = `-- name: UpdateCardioAndSets :one
UPDATE cardio_and_sets
SET
    set_number = $1,
    distance = $2,
    is_kilometers = $3,
    duration_seconds = $4,
    updated_at = NOW()
WHERE id = $5 AND workout_exercises_id = $6
RETURNING id, workout_exercises_id, set_number, distance, is_kilometers, duration_seconds, created_at, updated_at
`

type UpdateCardioAndSetsParams struct {
	SetNumber          int32
	Distance           sql.NullFloat64
	IsKilometers       bool
	DurationSeconds    sql.NullInt32
	ID                 uuid.UUID
	WorkoutExercisesID uuid.UUID
}

func (q *Queries) UpdateCardioAndSets(ctx context.Context, arg UpdateCardioAndSetsParams) (CardioAndSet, error) {
	row := q.db.QueryRowContext(ctx, updateCardioAndSets,
		arg.SetNumber,
		arg.Distance,
		arg.IsKilometers,
		arg.DurationSeconds,
		arg.ID,
		arg.WorkoutExercisesID,
	)
	var i CardioAndSet
	err := row.Scan(
		&i.ID,
		&i.WorkoutExercisesID,
		&i.SetNumber,
		&i.Distance,
		&i.IsKilometers,
		&i.DurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
