// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercises.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createExercises = `-- name: CreateExercises :one
INSERT INTO exercises(id, user_id, exercise_name, target_muscles, equipment, difficulty_level, description, created_at, updated_at)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, user_id, exercise_name, target_muscles, equipment, difficulty_level, created_at, updated_at, description
`

type CreateExercisesParams struct {
	ID              uuid.UUID
	UserID          uuid.NullUUID
	ExerciseName    string
	TargetMuscles   []string
	Equipment       sql.NullString
	DifficultyLevel sql.NullString
	Description     sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateExercises(ctx context.Context, arg CreateExercisesParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, createExercises,
		arg.ID,
		arg.UserID,
		arg.ExerciseName,
		pq.Array(arg.TargetMuscles),
		arg.Equipment,
		arg.DifficultyLevel,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExerciseName,
		pq.Array(&i.TargetMuscles),
		&i.Equipment,
		&i.DifficultyLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
	)
	return i, err
}

const deleteExerciseByID = `-- name: DeleteExerciseByID :exec
DELETE FROM exercises
WHERE id = $1
`

func (q *Queries) DeleteExerciseByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteExerciseByID, id)
	return err
}

const getExerciseFromID = `-- name: GetExerciseFromID :one
SELECT id, user_id, exercise_name, target_muscles, equipment, difficulty_level, created_at, updated_at, description FROM exercises
WHERE id = $1
`

func (q *Queries) GetExerciseFromID(ctx context.Context, id uuid.UUID) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getExerciseFromID, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExerciseName,
		pq.Array(&i.TargetMuscles),
		&i.Equipment,
		&i.DifficultyLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
	)
	return i, err
}

const getExerciseFromName = `-- name: GetExerciseFromName :one
SELECT id, user_id, exercise_name, target_muscles, equipment, difficulty_level, created_at, updated_at, description FROM exercises
WHERE exercise_name = $1
`

func (q *Queries) GetExerciseFromName(ctx context.Context, exerciseName string) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getExerciseFromName, exerciseName)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExerciseName,
		pq.Array(&i.TargetMuscles),
		&i.Equipment,
		&i.DifficultyLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
	)
	return i, err
}

const getExercisesFromUser = `-- name: GetExercisesFromUser :many
SELECT id, user_id, exercise_name, target_muscles, equipment, difficulty_level, created_at, updated_at, description FROM exercises
WHERE user_id = $1
`

func (q *Queries) GetExercisesFromUser(ctx context.Context, userID uuid.NullUUID) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, getExercisesFromUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExerciseName,
			pq.Array(&i.TargetMuscles),
			&i.Equipment,
			&i.DifficultyLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSameDifficultyExercises = `-- name: GetSameDifficultyExercises :many
SELECT id, user_id, exercise_name, target_muscles, equipment, difficulty_level, created_at, updated_at, description FROM exercises
WHERE difficulty_level = $1
`

func (q *Queries) GetSameDifficultyExercises(ctx context.Context, difficultyLevel sql.NullString) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, getSameDifficultyExercises, difficultyLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExerciseName,
			pq.Array(&i.TargetMuscles),
			&i.Equipment,
			&i.DifficultyLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSameEquipmentExercises = `-- name: GetSameEquipmentExercises :many
SELECT id, user_id, exercise_name, target_muscles, equipment, difficulty_level, created_at, updated_at, description FROM exercises
WHERE equipment = $1
`

func (q *Queries) GetSameEquipmentExercises(ctx context.Context, equipment sql.NullString) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, getSameEquipmentExercises, equipment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExerciseName,
			pq.Array(&i.TargetMuscles),
			&i.Equipment,
			&i.DifficultyLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSameMuscleExercises = `-- name: GetSameMuscleExercises :many
SELECT id, user_id, exercise_name, target_muscles, equipment, difficulty_level, created_at, updated_at, description FROM exercises
WHERE $1 = ANY(target_muscles)
`

func (q *Queries) GetSameMuscleExercises(ctx context.Context, targetMuscles []string) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, getSameMuscleExercises, pq.Array(targetMuscles))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExerciseName,
			pq.Array(&i.TargetMuscles),
			&i.Equipment,
			&i.DifficultyLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
