// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CardioAndSet struct {
	ID                 uuid.UUID
	WorkoutExercisesID uuid.UUID
	SetNumber          int32
	Distance           sql.NullString
	IsKilometers       bool
	DurationSeconds    sql.NullInt32
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Exercise struct {
	ID              uuid.UUID
	UserID          uuid.NullUUID
	ExerciseName    string
	TargetMuscles   []string
	Equipment       sql.NullString
	DifficultyLevel sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Description     sql.NullString
}

type RefreshToken struct {
	HashedToken string
	UserID      uuid.UUID
	ExpiresAt   time.Time
	IsRevoked   bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type WeightsAndSet struct {
	ID                 uuid.UUID
	WorkoutExercisesID uuid.UUID
	Weight             string
	IsKilograms        bool
	SetNumber          int32
	RepsTarget         int32
	RepsActual         int32
	DurationSeconds    sql.NullInt32
	RestTimeSeconds    sql.NullInt32
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type WorkoutExercise struct {
	ID               uuid.UUID
	WorkoutSessionID uuid.UUID
	ExerciseID       uuid.UUID
	OrderIndex       int32
	Notes            sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type WorkoutSession struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	WorkoutDate time.Time
	Description sql.NullString
	Notes       sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
