// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens(hashed_token, user_id, expires_at, created_at, updated_at)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING hashed_token, user_id, expires_at, is_revoked, created_at, updated_at
`

type CreateRefreshTokenParams struct {
	HashedToken string
	UserID      uuid.UUID
	ExpiresAt   time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken,
		arg.HashedToken,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.HashedToken,
		&i.UserID,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT hashed_token, user_id, expires_at, is_revoked, created_at, updated_at FROM refresh_tokens
WHERE hashed_token = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, hashedToken string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, hashedToken)
	var i RefreshToken
	err := row.Scan(
		&i.HashedToken,
		&i.UserID,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens
SET is_revoked = true, updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET is_revoked = true, updated_at = NOW()
WHERE hashed_token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, hashedToken string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, hashedToken)
	return err
}
