// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weights_and_sets.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createWeightsAndSets = `-- name: CreateWeightsAndSets :one
INSERT INTO weights_and_sets(id, workout_exercises_id, weight, is_kilograms, set_number, reps_target, reps_actual, duration_seconds, rest_time_seconds, created_at, updated_at)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, workout_exercises_id, weight, is_kilograms, set_number, reps_target, reps_actual, duration_seconds, rest_time_seconds, created_at, updated_at
`

type CreateWeightsAndSetsParams struct {
	ID                 uuid.UUID
	WorkoutExercisesID uuid.UUID
	Weight             float64
	IsKilograms        bool
	SetNumber          int32
	RepsTarget         int32
	RepsActual         int32
	DurationSeconds    sql.NullInt32
	RestTimeSeconds    sql.NullInt32
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) CreateWeightsAndSets(ctx context.Context, arg CreateWeightsAndSetsParams) (WeightsAndSet, error) {
	row := q.db.QueryRowContext(ctx, createWeightsAndSets,
		arg.ID,
		arg.WorkoutExercisesID,
		arg.Weight,
		arg.IsKilograms,
		arg.SetNumber,
		arg.RepsTarget,
		arg.RepsActual,
		arg.DurationSeconds,
		arg.RestTimeSeconds,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i WeightsAndSet
	err := row.Scan(
		&i.ID,
		&i.WorkoutExercisesID,
		&i.Weight,
		&i.IsKilograms,
		&i.SetNumber,
		&i.RepsTarget,
		&i.RepsActual,
		&i.DurationSeconds,
		&i.RestTimeSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWeightAndSets = `-- name: DeleteWeightAndSets :exec
DELETE FROM weights_and_sets
WHERE id = $1 AND workout_exercises_id = $2
`

type DeleteWeightAndSetsParams struct {
	ID                 uuid.UUID
	WorkoutExercisesID uuid.UUID
}

func (q *Queries) DeleteWeightAndSets(ctx context.Context, arg DeleteWeightAndSetsParams) error {
	_, err := q.db.ExecContext(ctx, deleteWeightAndSets, arg.ID, arg.WorkoutExercisesID)
	return err
}

const getAllSetsFromSession = `-- name: GetAllSetsFromSession :many
SELECT id, workout_exercises_id, weight, is_kilograms, set_number, reps_target, reps_actual, duration_seconds, rest_time_seconds, created_at, updated_at FROM weights_and_sets
WHERE workout_exercises_id = $1
`

func (q *Queries) GetAllSetsFromSession(ctx context.Context, workoutExercisesID uuid.UUID) ([]WeightsAndSet, error) {
	rows, err := q.db.QueryContext(ctx, getAllSetsFromSession, workoutExercisesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeightsAndSet
	for rows.Next() {
		var i WeightsAndSet
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutExercisesID,
			&i.Weight,
			&i.IsKilograms,
			&i.SetNumber,
			&i.RepsTarget,
			&i.RepsActual,
			&i.DurationSeconds,
			&i.RestTimeSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetVolume = `-- name: GetSetVolume :one
SELECT (reps_actual * weight)::float8 FROM weights_and_sets
WHERE id = $1 AND workout_exercises_id = $2
`

type GetSetVolumeParams struct {
	ID                 uuid.UUID
	WorkoutExercisesID uuid.UUID
}

func (q *Queries) GetSetVolume(ctx context.Context, arg GetSetVolumeParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, getSetVolume, arg.ID, arg.WorkoutExercisesID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalDuration = `-- name: GetTotalDuration :one
SELECT COALESCE(duration_seconds, 0) + COALESCE(rest_time_seconds, 0) FROM weights_and_sets
WHERE id = $1 AND workout_exercises_id = $2
`

type GetTotalDurationParams struct {
	ID                 uuid.UUID
	WorkoutExercisesID uuid.UUID
}

func (q *Queries) GetTotalDuration(ctx context.Context, arg GetTotalDurationParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getTotalDuration, arg.ID, arg.WorkoutExercisesID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalDurationForAllSets = `-- name: GetTotalDurationForAllSets :one
SELECT COALESCE(SUM(COALESCE(duration_seconds, 0) + COALESCE(rest_time_seconds, 0)), 0)::int4 FROM weights_and_sets
WHERE workout_exercises_id = $1
`

func (q *Queries) GetTotalDurationForAllSets(ctx context.Context, workoutExercisesID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getTotalDurationForAllSets, workoutExercisesID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalVolumeFromAllSets = `-- name: GetTotalVolumeFromAllSets :one
SELECT COALESCE(SUM(reps_actual * weight), 0)::float8 FROM weights_and_sets
WHERE workout_exercises_id = $1
`

func (q *Queries) GetTotalVolumeFromAllSets(ctx context.Context, workoutExercisesID uuid.UUID) (float64, error) {
	row := q.db.QueryRowContext(ctx, getTotalVolumeFromAllSets, workoutExercisesID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const getWeightAndSetFromID = `-- name: GetWeightAndSetFromID :one
SELECT id, workout_exercises_id, weight, is_kilograms, set_number, reps_target, reps_actual, duration_seconds, rest_time_seconds, created_at, updated_at FROM weights_and_sets
WHERE id = $1
`

func (q *Queries) GetWeightAndSetFromID(ctx context.Context, id uuid.UUID) (WeightsAndSet, error) {
	row := q.db.QueryRowContext(ctx, getWeightAndSetFromID, id)
	var i WeightsAndSet
	err := row.Scan(
		&i.ID,
		&i.WorkoutExercisesID,
		&i.Weight,
		&i.IsKilograms,
		&i.SetNumber,
		&i.RepsTarget,
		&i.RepsActual,
		&i.DurationSeconds,
		&i.RestTimeSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWeightsAndSets = `-- name: UpdateWeightsAndSets :one
UPDATE weights_and_sets
SET
    weight = $1,
    is_kilograms = $2,
    set_number = $3,
    reps_target = $4,
    reps_actual = $5,
    duration_seconds = $6,
    rest_time_seconds = $7,
    updated_at = NOW()
WHERE id = $8 AND workout_exercises_id = $9
RETURNING id, workout_exercises_id, weight, is_kilograms, set_number, reps_target, reps_actual, duration_seconds, rest_time_seconds, created_at, updated_at
`

type UpdateWeightsAndSetsParams struct {
	Weight             float64
	IsKilograms        bool
	SetNumber          int32
	RepsTarget         int32
	RepsActual         int32
	DurationSeconds    sql.NullInt32
	RestTimeSeconds    sql.NullInt32
	ID                 uuid.UUID
	WorkoutExercisesID uuid.UUID
}

func (q *Queries) UpdateWeightsAndSets(ctx context.Context, arg UpdateWeightsAndSetsParams) (WeightsAndSet, error) {
	row := q.db.QueryRowContext(ctx, updateWeightsAndSets,
		arg.Weight,
		arg.IsKilograms,
		arg.SetNumber,
		arg.RepsTarget,
		arg.RepsActual,
		arg.DurationSeconds,
		arg.RestTimeSeconds,
		arg.ID,
		arg.WorkoutExercisesID,
	)
	var i WeightsAndSet
	err := row.Scan(
		&i.ID,
		&i.WorkoutExercisesID,
		&i.Weight,
		&i.IsKilograms,
		&i.SetNumber,
		&i.RepsTarget,
		&i.RepsActual,
		&i.DurationSeconds,
		&i.RestTimeSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
