// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workout_sessions.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createWorkoutSessions = `-- name: CreateWorkoutSessions :one
INSERT INTO workout_sessions(id, user_id, workout_date, description, notes, created_at, updated_at)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, user_id, workout_date, description, notes, created_at, updated_at
`

type CreateWorkoutSessionsParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	WorkoutDate time.Time
	Description sql.NullString
	Notes       sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateWorkoutSessions(ctx context.Context, arg CreateWorkoutSessionsParams) (WorkoutSession, error) {
	row := q.db.QueryRowContext(ctx, createWorkoutSessions,
		arg.ID,
		arg.UserID,
		arg.WorkoutDate,
		arg.Description,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutDate,
		&i.Description,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkoutSession = `-- name: DeleteWorkoutSession :exec
DELETE FROM workout_sessions
WHERE id = $1 AND user_id = $2
`

type DeleteWorkoutSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteWorkoutSession(ctx context.Context, arg DeleteWorkoutSessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkoutSession, arg.ID, arg.UserID)
	return err
}

const getAllWorkoutSessionsSorted = `-- name: GetAllWorkoutSessionsSorted :many
SELECT id, user_id, workout_date, description, notes, created_at, updated_at FROM workout_sessions
WHERE user_id = $1
ORDER BY workout_date DESC
`

func (q *Queries) GetAllWorkoutSessionsSorted(ctx context.Context, userID uuid.UUID) ([]WorkoutSession, error) {
	rows, err := q.db.QueryContext(ctx, getAllWorkoutSessionsSorted, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutSession
	for rows.Next() {
		var i WorkoutSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkoutDate,
			&i.Description,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastWorkoutSession = `-- name: GetLastWorkoutSession :one
SELECT id, user_id, workout_date, description, notes, created_at, updated_at FROM workout_sessions
WHERE user_id = $1
ORDER BY workout_date DESC
`

func (q *Queries) GetLastWorkoutSession(ctx context.Context, userID uuid.UUID) (WorkoutSession, error) {
	row := q.db.QueryRowContext(ctx, getLastWorkoutSession, userID)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutDate,
		&i.Description,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkoutSessionByID = `-- name: GetWorkoutSessionByID :one
SELECT id, user_id, workout_date, description, notes, created_at, updated_at FROM workout_sessions
WHERE id = $1
`

func (q *Queries) GetWorkoutSessionByID(ctx context.Context, id uuid.UUID) (WorkoutSession, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutSessionByID, id)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutDate,
		&i.Description,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkoutSessionsCount = `-- name: GetWorkoutSessionsCount :one
SELECT COUNT(*) FROM workout_sessions
WHERE user_id = $1
`

func (q *Queries) GetWorkoutSessionsCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutSessionsCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
