// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workout_exercises.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createWorkoutExercises = `-- name: CreateWorkoutExercises :one
INSERT INTO workout_exercises(id, workout_session_id, exercise_id, order_index, notes, created_at, updated_at)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, workout_session_id, exercise_id, order_index, notes, created_at, updated_at
`

type CreateWorkoutExercisesParams struct {
	ID               uuid.UUID
	WorkoutSessionID uuid.UUID
	ExerciseID       uuid.UUID
	OrderIndex       int32
	Notes            sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) CreateWorkoutExercises(ctx context.Context, arg CreateWorkoutExercisesParams) (WorkoutExercise, error) {
	row := q.db.QueryRowContext(ctx, createWorkoutExercises,
		arg.ID,
		arg.WorkoutSessionID,
		arg.ExerciseID,
		arg.OrderIndex,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i WorkoutExercise
	err := row.Scan(
		&i.ID,
		&i.WorkoutSessionID,
		&i.ExerciseID,
		&i.OrderIndex,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkoutExercises = `-- name: DeleteWorkoutExercises :exec
DELETE FROM workout_exercises
WHERE id = $1 AND workout_session_id = $2
`

type DeleteWorkoutExercisesParams struct {
	ID               uuid.UUID
	WorkoutSessionID uuid.UUID
}

func (q *Queries) DeleteWorkoutExercises(ctx context.Context, arg DeleteWorkoutExercisesParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkoutExercises, arg.ID, arg.WorkoutSessionID)
	return err
}

const getNumberOfExercisesInWorkout = `-- name: GetNumberOfExercisesInWorkout :one
SELECT COUNT(*) FROM workout_exercises
WHERE workout_session_id = $1
`

func (q *Queries) GetNumberOfExercisesInWorkout(ctx context.Context, workoutSessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNumberOfExercisesInWorkout, workoutSessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWorkoutExerciseFromID = `-- name: GetWorkoutExerciseFromID :one
SELECT id, workout_session_id, exercise_id, order_index, notes, created_at, updated_at FROM workout_exercises
WHERE id = $1
`

func (q *Queries) GetWorkoutExerciseFromID(ctx context.Context, id uuid.UUID) (WorkoutExercise, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutExerciseFromID, id)
	var i WorkoutExercise
	err := row.Scan(
		&i.ID,
		&i.WorkoutSessionID,
		&i.ExerciseID,
		&i.OrderIndex,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkoutsInSession = `-- name: GetWorkoutsInSession :many
SELECT id, workout_session_id, exercise_id, order_index, notes, created_at, updated_at FROM workout_exercises
WHERE workout_session_id = $1
ORDER BY order_index
`

func (q *Queries) GetWorkoutsInSession(ctx context.Context, workoutSessionID uuid.UUID) ([]WorkoutExercise, error) {
	rows, err := q.db.QueryContext(ctx, getWorkoutsInSession, workoutSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutExercise
	for rows.Next() {
		var i WorkoutExercise
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutSessionID,
			&i.ExerciseID,
			&i.OrderIndex,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkoutExercise = `-- name: UpdateWorkoutExercise :one
UPDATE workout_exercises
SET exercise_id = $1, order_index = $2, notes = $3, updated_at = NOW()
WHERE id = $4 AND workout_session_id = $5
RETURNING id, workout_session_id, exercise_id, order_index, notes, created_at, updated_at
`

type UpdateWorkoutExerciseParams struct {
	ExerciseID       uuid.UUID
	OrderIndex       int32
	Notes            sql.NullString
	ID               uuid.UUID
	WorkoutSessionID uuid.UUID
}

func (q *Queries) UpdateWorkoutExercise(ctx context.Context, arg UpdateWorkoutExerciseParams) (WorkoutExercise, error) {
	row := q.db.QueryRowContext(ctx, updateWorkoutExercise,
		arg.ExerciseID,
		arg.OrderIndex,
		arg.Notes,
		arg.ID,
		arg.WorkoutSessionID,
	)
	var i WorkoutExercise
	err := row.Scan(
		&i.ID,
		&i.WorkoutSessionID,
		&i.ExerciseID,
		&i.OrderIndex,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkoutExerciseOrder = `-- name: UpdateWorkoutExerciseOrder :one
UPDATE workout_exercises
SET order_index = $1, updated_at = NOW()
WHERE id = $2 AND workout_session_id = $3
RETURNING id, workout_session_id, exercise_id, order_index, notes, created_at, updated_at
`

type UpdateWorkoutExerciseOrderParams struct {
	OrderIndex       int32
	ID               uuid.UUID
	WorkoutSessionID uuid.UUID
}

func (q *Queries) UpdateWorkoutExerciseOrder(ctx context.Context, arg UpdateWorkoutExerciseOrderParams) (WorkoutExercise, error) {
	row := q.db.QueryRowContext(ctx, updateWorkoutExerciseOrder, arg.OrderIndex, arg.ID, arg.WorkoutSessionID)
	var i WorkoutExercise
	err := row.Scan(
		&i.ID,
		&i.WorkoutSessionID,
		&i.ExerciseID,
		&i.OrderIndex,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
